### ISSUE TITLE
Log creation failed.

### ISSUE THREAD

**Issue by KevinL852** [KevinL852/SirenSetting_Limit_Adjuster#2]
Some people are currently experiencing the following error: "SirenSetting_Limit_Adjuster log creation failed. Logging has been disabled. Error: Access is denied."

This is being investigated.

**Comment by KevinL852** [comment]
To fix the error you need to give the 'Users' group (Users (PCNAME\Users)) write permissions for your 'Grand Theft Auto V' folder.

How to do this:
1. Go to your 'Grand Theft Auto V' folder and right click it'
2. Click properties and go to the 'Security' tab
3. Click on 'Advanced'
4. Click on 'Change permissions'
5. Click on the 'Users (PCNAME\Users)' group
6. Tick the 'Write' checkbox and click on 'OK'
7. Click on 'Apply'
8. Click on 'OK' and launch FiveM.

This should solve the Log creation error.

**Comment by GGRP21** [comment]
Tried that, didnt work. Any suggestions?

**Comment by KevinL852** [comment]
> Tried that, didnt work. Any suggestions?

Hello, sorry for the late reply.
Unfortunately, I do not know of any other way to fix this issue.
If you have multiple GTA V installations, make sure you apply the changes to the installation folder that is used by FiveM.
