### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Michael21107** [KevinL852/SirenSetting_Limit_Adjuster#3]
isn't this the same as [this](https://www.lcpdfr.com/downloads/gta5mods/scripts/44272-sirensetting-limit-adjuster-fixed-for-every-fivem-build/?tab=comments&sort=newest)?

**Comment by KevinL852** [comment]
Hello,

Yes it is, the reason this exists was mainly for build 2802 as the original creator hadn't updated it to that gamebuild when the server I was on needed it, I didn't see that it has since been updated so I'll be removing this.
